version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    container_name: otc-php
    ports:
      - "8080:80"
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: otc-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otcsystems
      MYSQL_USER: otc_user
      MYSQL_PASSWORD: change_me
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
      - otc-mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: otc-adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  otc-mysql-data:
